name: Fetch Instagram (daily insights) [DISABLED]

# ※このWorkflowは旧版です。新しい "fetch-daily-insights.yml" に統合済み。
# 手動実行のみ許可し、スケジュールを無効化します。

on:
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  fetch-daily:
    strategy:
      matrix:
        env: [KITAKYUSHU, HONAMI, YUMEGAOKA, IRISO, OHTU]
    concurrency:
      group: fetch-daily-${{ github.ref }}-${{ matrix.env }} 
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    timeout-minutes: 10
  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "18" }
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node18-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-node18-

      - name: Debug (event & time)
        run: |
          echo "event_name=${{ github.event_name }}"
          node -e "console.log('now(UTC)=', new Date().toISOString())"

      - name: Debug token & mapping (preflight)
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          IG_ID:         ${{ secrets.IG_ID }}
          PAGE_ID:       "785461964653257"
        run: |
          echo "IG_ID=$IG_ID"
          node -e "const t=process.env.FB_PAGE_TOKEN; console.log('TOKEN_HEAD_TAIL=', t? t.slice(0,8)+'...'+t.slice(-6) : 'none')"
          # USER判定：/me/accounts が成功すれば USER トークン
          node -e "const u=new URLSearchParams({fields:'id,name,instagram_business_account{id,username}',access_token:process.env.FB_PAGE_TOKEN}); fetch('https://graph.facebook.com/v23.0/me/accounts?'+u.toString()).then(r=>r.text()).then(t=>console.log('ME_ACCOUNTS=',t)).catch(e=>console.error(e))"
          # ページ→IGの実紐づけ
          node -e "const u=new URLSearchParams({fields:'instagram_business_account{id,username}',access_token:process.env.FB_PAGE_TOKEN}); fetch('https://graph.facebook.com/v23.0/'+process.env.PAGE_ID+'?'+u.toString()).then(r=>r.text()).then(t=>console.log('PAGE_LOOKUP=',t)).catch(e=>console.error(e))"
          # IGユーザー直アクセス可否
          node -e "const u=new URLSearchParams({fields:'id,username',access_token:process.env.FB_PAGE_TOKEN}); fetch('https://graph.facebook.com/v23.0/'+process.env.IG_ID+'?'+u.toString()).then(r=>r.text()).then(t=>console.log('IG_BASIC=',t)).catch(e=>console.error(e))"
          # Insights最小（切り分け用）
          node -e "const u=new URLSearchParams({metric:'impressions',period:'day',access_token:process.env.FB_PAGE_TOKEN}); fetch('https://graph.facebook.com/v23.0/'+process.env.IG_ID+'/insights?'+u.toString()).then(r=>r.text()).then(t=>console.log('IG_INSIGHTS=',t)).catch(e=>console.error(e))"

      - name: Debug whoami (token & ig-id)
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          IG_ID: ${{ secrets.IG_ID }}
        run: |
          echo "IG_ID=$IG_ID"
          node -e "const f=process.env.FB_PAGE_TOKEN; console.log('TOKEN_HEAD_TAIL=', f?f.slice(0,8)+'...'+f.slice(-6):'none')"
          node -e "const u=new URLSearchParams({fields:'id,username',access_token:process.env.FB_PAGE_TOKEN}); fetch('https://graph.facebook.com/v23.0/'+process.env.IG_ID+'?'+u.toString()).then(r=>r.text()).then(t=>console.log(t)).catch(e=>console.error(e))"

      - name: Run collector (account insights daily)
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          IG_ID: ${{ secrets.IG_ID }}
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
        run: |
          set -e
          ok=""
          for i in 1 2 3; do
            echo "Run collector try #$i ..."
            node scripts/collectors/account_insights_daily.mjs && { ok="yes"; break; } || true
            # 指数バックオフ（5s, 20s, 45s）
            sleep $(( i*i*5 ))
          done
          if [ -z "$ok" ]; then 
          echo "Collector failed after 3 attempts" >&2
            exit 1
          fi
      - name: Commit & push if changed
        run: |
          # 追跡済み変更・未追跡ファイルの両方を検出
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes; skip commit."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # ブランチ名を GITHUB_REF から安全に抽出（例: refs/heads/main → main）
          BRANCH="${GITHUB_REF#refs/heads/}"
          if [ -z "$BRANCH" ] || [ "$BRANCH" = "$GITHUB_REF" ]; then
            echo "Not on a branch (GITHUB_REF=$GITHUB_REF). Skip commit/push."
            exit 0
          fi
          # ブランチに乗り換え（detached HEAD 回避）
          git switch -C "$BRANCH"
          git add -A
          git commit -m "chore: update daily insights [skip ci]"
          # 並行実行（マトリクス）での push 競合を回避：pull --rebase → push をリトライ
          tries=0
          while :; do
            tries=$((tries+1))
            # 最新を取り込んで自分のコミットを先頭へ
            git pull --rebase origin "$BRANCH" || true
            # push（成功なら抜ける）
            if git push origin HEAD:"$BRANCH"; then
              echo "Pushed successfully on try #$tries"
              break
            fi
            # 5回まで指数的に待って再試行
            test $tries -ge 5 && { echo "Push failed after $tries retries" >&2; exit 1; }
            sleep $(( tries * 3 ))
          done   
      - name: Upload data artifact (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: daily-insights-${{ matrix.env }}-${{ github.run_id }}
          path: |
            data/**
          if-no-files-found: warn
          retention-days: 14
      - name: Post summary (success)
        if: ${{ success() }}
        run: |
          {
            echo "### Daily insights: success";
            echo "- Event: ${{ github.event_name }}";
            echo "- Ref:    ${{ github.ref }}";
            echo "- Run ID: ${{ github.run_id }}";
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Post summary (failure)
        if: ${{ failure() }}
        run: |
          {
            echo "### Daily insights: **FAILED**";
            echo "- Event: ${{ github.event_name }}";
            echo "- Ref:    ${{ github.ref }}";
            echo "- Run ID: ${{ github.run_id }}";
            echo "";
            echo "Collector retried 3 times and gave up.";
          } >> "$GITHUB_STEP_SUMMARY"
