name: Fetch Instagram (hourly followers)

on:
  schedule:
    - cron: "0 * * * *"  # 毎時00分（UTC）
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch-hourly-followers:
    strategy:
      matrix:
        env: [KITAKYUSHU, HONAMI, YUMEGAOKA, IRISO, OHTU]
    concurrency:
      group: fetch-hourly-followers-${{ github.ref }}-${{ matrix.env }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "18" }
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node18-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm install --prefer-offline --no-audit
      - name: Run collector (followers hourly)
        env:
          IG_ID: ${{ secrets.IG_ID }}
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          RUN_MODE: hourly_followers
        run: node scripts/fetch_followers_api.mjs
      - name: Duplicate to hourly path (and update latest_hourly.json)
        shell: bash
        run: |
          set -euo pipefail
          # 直近の変更ファイル（収集で生成された日次ファイル）を検出
          changed=$(git status --porcelain | awk '{print $2}' | grep -E '^data/account/.+/[0-9]{4}-[0-9]{2}-[0-9]{2}\.json$' || true)
          if [ -z "${changed}" ]; then
            echo "No daily JSON changes found under data/account/**. Skip hourly duplication."
            exit 0
          fi
          echo "Changed daily files:" $changed
          # 時刻は generated_at を優先。無ければ現在時刻(UTC)を使用
          for f in $changed; do
            node -e '
              const fs=require("fs"), p=process.argv[1];
              const j=JSON.parse(fs.readFileSync(p,"utf8"));
              const acc = j.account;
              const date= j.date; // "YYYY-MM-DD"
              const d = j.generated_at ? new Date(j.generated_at) : new Date();
              const HH = String(d.getUTCHours()).padStart(2,"0"); // UTCで揃える（Pages表示でJST換算可）
              const dir=`data/account/${acc}/hourly/${date}`;
              const out=`${dir}/${HH}.json`;
              fs.mkdirSync(dir,{recursive:true});
              fs.copyFileSync(p,out);
              fs.writeFileSync(`data/account/${acc}/latest_hourly.json`, JSON.stringify(j,null,2));
              console.log("wrote", out, "and updated latest_hourly.json");
            ' "$f"
          done      
      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data/account
          if ! git diff --cached --quiet; then
            git commit -m "chore: update hourly followers for ${{ matrix.env }} [skip ci]"
            git push
          fi
